---

- name: Build environment | Install additional packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - perl-core
    - openjade
    - opensp
    - docbook-dtds
    - docbook-style-dsssl
    - icu
    - libicu
    - libicu-devel
    - readline-devel
    - zlib-devel
    - openssl-devel
    - pam-devel
    - python-devel
    - krb5-devel
    - libxml2-devel
    - libxslt-devel
    - openldap-devel
    - e2fsprogs-devel
    - tcl-devel

- name: Build environment | Link create
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: /usr/lib64/libicuuc.so, dest: /usr/local/lib64/libicuuc.so.46 }
    - { src: /usr/lib64/libicuuc.so, dest: /usr/local/lib/libicuuc.so.46 }
    - { src: /usr/lib64/libicudata.so, dest: /usr/local/lib64/libicudata.so.46 }
    - { src: /usr/lib64/libicudata.so, dest: /usr/local/lib/libicudata.so.46 }
    - { src: /usr/lib64/libicui18n.so, dest: /usr/local/lib64/libicui18n.so.46 }
    - { src: /usr/lib64/libicui18n.so, dest: /usr/local/lib/libicui18n.so.46 }
