---

- name: Package preparation | Source download
  get_url:
    url: "http://v8.1c.ru/overview/postgresql_patches/9-4-2/postgresql94-9.4.2-1.1c.src.rpm"
    dest: /root/postgresql94-9.4.2-1.1c.src.rpm

- name: Package preparation | Source install
  shell: rpm -i /root/postgresql94-9.4.2-1.1c.src.rpm

- name: Package preparation | Source patch
  patch:
    src: macros.patch
    dest: /usr/lib/rpm/macros
    remote_src: False

- name: Package preparation | Source build
  shell: "cd /root && rpmbuild -bb --define='runselftest 0' /root/rpmbuild/SPECS/postgresql-9.4.2.spec && touch /root/pgsql_build.done"
  args:
    creates: /root/pgsql_build.done
