---

- name: Postgres configure | Remove old data directory
  file:
    path: /var/lib/pgsql/9.4
    state: absent

- name: Postgres configure | Change permissions new data directory
  file:
    path: "{{ pg_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Postgres configure | Create link to new data directory
  file:
    src: "{{ pg_data_dir }}"
    dest: /var/lib/pgsql/9.4
    state: link
    owner: postgres
    group: postgres

- name: Postgres configure | Initializing database
  shell: service postgresql-9.4 initdb ru_RU.UTF-8
  notify: postgresql started

- name: Postgres configure | Copy auth configure file
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.4/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600

- name: Postgres configure | Firewall reconfigure
  firewalld:
    zone: public
    service: postgresql
    permanent: true
    state: enabled
  notify: firewall restarted
