---

- name: Build environment
  include: 01-build-environment.yml

- name: Package preparation
  include: 02-package-preparation.yml

- name: Postgres install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - /root/rpmbuild/RPMS/x86_64/postgresql94-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-contrib-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-debuginfo-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-devel-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-docs-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-libs-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-plperl-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-plpython-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-server-9.4.2-1.1C.x86_64.rpm
  - /root/rpmbuild/RPMS/x86_64/postgresql94-test-9.4.2-1.1C.x86_64.rpm

- name: Postgres configure
  include: 03-postgres-configure.yml
