---

- name: Remote control | X11vnc packages install
  yum:
    name: x11vnc
    enablerepo: epel
    state: present

- name: Remote control | Copy config file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: x11vnc.pass, dest: /etc/x11vnc.pass }
    - { src: x11vnc.service, dest: /etc/systemd/system/x11vnc.service }
  notify: x11vnc restarted

- name: Remote control | Firewall reconfigure
  firewalld:
    zone: public
    port: "5900/tcp"
    permanent: true
    state: enabled
  notify: firewall restarted
